### ISSUE TITLE
react project

### ISSUE THREAD

**Issue by chen-jieyi** [iaalm/react-qrcode#2]
./node_modules/_react-qrcode@0.1.3@react-qrcode/QRcode.js 89:4
Module parse failed: Unexpected token (89:4)
You may need an appropriate loader to handle this file type.
| 	render: function() {
| 		return (
> 				<div id='qrcode' ref='qrcode' />
| 		)
| 	}

**Comment by JounQin** [comment]
@chen-jieyi You can try `react-qrcode@0.2.0` which is rewritten from scratch now.
