### ISSUE TITLE
Package maintenance or transfer npm pkg?

### ISSUE THREAD

**Issue by JounQin** [iaalm/react-qrcode#3]
Hi @iaalm,

First thanks very much for creating this component, and I tried it in my own project several days ago, but then I found it just could not work correctly.

It seems that it's out of maintenance about 4 years, and the source code is outdated.

So my question here is, if you don't mind and don't want to maintain this package anymore, would you like to transfer the ownership of npm package? Its package name is nice and it would be great to let it be reborn and benefit the community.

My apologize for any rude requests.

Best wishes.

**Comment by iaalm** [comment]
That's a good idea. Just let me know you id, so that i can initialize the transfer.

**Comment by JounQin** [comment]
@iaalm My npm username is `jounqin`, thanks for response.

**Comment by JounQin** [comment]
Hi @iaalm, sorry to intercept, but did it make any progress?

**Comment by JounQin** [comment]
Thanks.
